[#-------------将数字转换成String 字符串--------]
[#function toString list="" listValue="" classType="int" ]
	[#if list?is_sequence || list?is_collection ]
		[#local string="" /]
		[#list list as item]
			[#if listValue=="" ]
				[#local value=item /]
			[#else ]
				[#local value=item[listValue] /]
			[/#if]
			[#local string=string+value /]
			[#if item_has_next ]
					[#if classType=="int" ]
						[#local string=string+"," /]
					[/#if]
			[/#if]
		[/#list]
		[#return string /]
	[#else]
		[#return list /]
	[/#if]
[/#function]